// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Comment struct {
	ID        pgtype.UUID      `db:"id" json:"id"`
	Owner     pgtype.UUID      `db:"owner" json:"owner"`
	Thread    pgtype.UUID      `db:"thread" json:"thread"`
	Content   string           `db:"content" json:"content"`
	Date      pgtype.Timestamp `db:"date" json:"date"`
	IsDeleted bool             `db:"is_deleted" json:"is_deleted"`
}

type RefreshToken struct {
	Token string `db:"token" json:"token"`
}

type Thread struct {
	ID    pgtype.UUID      `db:"id" json:"id"`
	Title string           `db:"title" json:"title"`
	Body  string           `db:"body" json:"body"`
	Date  pgtype.Timestamp `db:"date" json:"date"`
	Owner pgtype.UUID      `db:"owner" json:"owner"`
}

type User struct {
	ID        pgtype.UUID      `db:"id" json:"id"`
	Username  string           `db:"username" json:"username"`
	Password  string           `db:"password" json:"password"`
	Fullname  string           `db:"fullname" json:"fullname"`
	CreatedAt pgtype.Timestamp `db:"created_at" json:"created_at"`
	UpdatedAt pgtype.Timestamp `db:"updated_at" json:"updated_at"`
}
