// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: users.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createUser = `-- name: CreateUser :one
insert into users (id, username, password, name, created_at, updated_at) values(gen_random_uuid(), $1, $2, $3, now(), now()) returning id, username, name
`

type CreateUserParams struct {
	Username string
	Password string
	Name     string
}

type CreateUserRow struct {
	ID       uuid.UUID
	Username string
	Name     string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRowContext(ctx, createUser, arg.Username, arg.Password, arg.Name)
	var i CreateUserRow
	err := row.Scan(&i.ID, &i.Username, &i.Name)
	return i, err
}
