basePath: /
host: localhost:9000
info:
  contact: {}
  description: This is a Forum API
  title: Forum API
  version: "1.0"
paths: {}
securityDefinitions:
  "":
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
